# Generated by Django 4.2.3 on 2023-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aplicacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="nombre",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
