# Generated by Django 4.2.3 on 2023-08-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Aplicacion", "0002_servicio_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enfermero",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Aplicacion.persona",
                    ),
                ),
                ("especialidad", models.CharField(max_length=50)),
            ],
            bases=("Aplicacion.persona",),
        ),
        migrations.AddField(
            model_name="contrato",
            name="especialista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Aplicacion.enfermero",
            ),
        ),
    ]
