# Generated by Django 4.2.3 on 2023-08-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aplicacion", "0003_enfermero_contrato_especialista"),
    ]

    operations = [
        migrations.AddField(
            model_name="enfermero",
            name="matricula",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
